import * as stylex from "@stylexjs/stylex";
import { themeVars } from "./tokens.stylex";

export const workshopStyles = stylex.create({
  page: {
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
    margin: "0 auto",
    maxWidth: "74rem",
    padding: "2.5rem 1.5rem 4rem",
    width: "100%",
  },
  intro: {
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
    maxWidth: "46rem",
  },
  eyebrow: {
    color: themeVars.accent,
    fontSize: "0.75rem",
    fontWeight: 700,
    letterSpacing: "0.08em",
    margin: 0,
    textTransform: "uppercase",
  },
  title: {
    color: themeVars.textPrimary,
    fontSize: "clamp(1.875rem, 4vw, 2.75rem)",
    fontWeight: 600,
    letterSpacing: "-0.035em",
    lineHeight: 1.08,
    margin: 0,
  },
  copy: {
    color: themeVars.textSecondary,
    lineHeight: 1.6,
    margin: 0,
  },
  cardFrame: {
    width: "100%",
  },
  formRow: {
    alignItems: "end",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.875rem",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    gap: "0.5rem",
    minWidth: "15rem",
  },
  sectionHeader: {
    alignItems: "flex-start",
    borderBottomColor: themeVars.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.75rem",
    justifyContent: "space-between",
    paddingBottom: "1rem",
  },
  sectionTitle: {
    color: themeVars.textPrimary,
    fontSize: "1.5rem",
    fontWeight: 600,
    letterSpacing: "-0.025em",
    lineHeight: 1.2,
    margin: 0,
  },
  meta: {
    color: themeVars.textSubtle,
    fontSize: "0.875rem",
    lineHeight: 1.45,
    margin: 0,
  },
  status: {
    backgroundColor: themeVars.accentMuted,
    borderRadius: themeVars.radiusSmall,
    color: themeVars.textPrimary,
    fontSize: "0.8125rem",
    fontWeight: 650,
    margin: 0,
    padding: "0.375rem 0.625rem",
  },
  grid: {
    display: "grid",
    gap: "1rem",
    gridTemplateColumns: "repeat(auto-fit, minmax(18rem, 1fr))",
  },
  stack: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  compactStack: {
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  listItem: {
    borderBottomColor: themeVars.border,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    paddingBottom: "0.75rem",
  },
  actionRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.625rem",
  },
  actionLink: {
    backgroundColor: {
      default: "transparent",
      ':hover': themeVars.accentMuted,
    },
    borderColor: themeVars.border,
    borderRadius: themeVars.radiusSmall,
    borderStyle: "solid",
    borderWidth: "1px",
    color: themeVars.textPrimary,
    fontSize: "0.875rem",
    fontWeight: 600,
    padding: "0.625rem 0.875rem",
    textDecoration: "none",
  },
  alert: {
    backgroundColor: themeVars.dangerMuted,
    borderColor: themeVars.danger,
    borderLeftStyle: "solid",
    borderLeftWidth: "3px",
    borderRadius: themeVars.radiusSmall,
    color: themeVars.textPrimary,
    margin: 0,
    padding: "0.75rem 0.875rem",
  },
});
