import type { Manuscript, Source } from "../domain/index";
import { collectNodeIds } from "../domain/manuscript";
import type { SourceProfile } from "../domain/sourceProfile";
import type { PlanningBrief } from "../domain/planningBrief";
import type { Citation } from "../domain/citation";
import type { ContentRelation } from "../domain/contentRelation";
import type { EditorialPlan } from "../domain/editorialPlan";
import type { EvidencePack } from "../domain/draftUnit";
import type {
  CorpusExplorer,
  RetrievedPassage,
  CorroborationProbe,
} from "./corpusExplorer";
import type { BibliographyDistributionEntry } from "../domain/bibliographyDistribution";

/**
 * Compatibility guard for persisted pre-Corpus-V2 workspace mappings.
 * This mapping is never documentary authority and cannot be generated by the core.
 */
export function assertDistributionValid(
  distribution: readonly BibliographyDistributionEntry[],
  manuscript: Manuscript
): void {
  const nodeIds = new Set(collectNodeIds(manuscript.tree));
  for (const entry of distribution) {
    if (!nodeIds.has(entry.scopeId)) {
      throw new Error(`Distribution scope '${entry.scopeId}' not found in manuscript`);
    }
  }
}

/** Source documentaire visible dans un scope, jamais le corpus intégral. */
export interface ProjectedSource {
  sourceId: string;
  title: string;
  authors: string[];
  subjects: string[];
  concepts: string[];
  abstract?: string;
}

export type DocumentaryRole = "supports" | "contradicts" | "qualifies" | "context";

export interface ProjectedPassage {
  passage: RetrievedPassage;
  role: DocumentaryRole;
  query: string;
}

/**
 * Projection transitoire et reconstruisible de la matière documentaire d'un scope.
 * Elle n'est ni un agrégat domaine ni une base canonique de preuves.
 */
export interface ProjectedScope {
  scopeId: string;
  sources: ProjectedSource[];
  passages: ProjectedPassage[];
  citationIds: string[];
  sourceRelationIds: string[];
  gaps: string[];
  unexploredAreas: string[];
}

export interface ProjectBibliographyInput {
  planningBrief: PlanningBrief;
  librarySources: readonly Source[];
  profiles: readonly SourceProfile[];
  citations?: readonly Citation[];
  relations?: readonly ContentRelation[];
  explorer?: CorpusExplorer;
  /** Contexte parent/voisins déjà résolu par l'appelant ; aucune lecture du manuscrit ici. */
  context?: readonly string[];
  limitPerProbe?: number;
}

/** Shared point Corpus V2 : projection documentaire passage-aware d'un scope. */
export function projectBibliography(input: ProjectBibliographyInput): Promise<ProjectedScope>;
/**
 * @deprecated Persisted-workspace read compatibility only.
 * The core no longer creates static source→scope distributions. New documentary
 * decisions must use the Corpus V2 ProjectBibliographyInput path above.
 */
export function projectBibliography(
  manuscript: Manuscript,
  distribution: readonly BibliographyDistributionEntry[],
  librarySources: readonly Source[],
  profiles: readonly SourceProfile[]
): ProjectedScope[];
export function projectBibliography(
  inputOrManuscript: ProjectBibliographyInput | Manuscript,
  distribution?: readonly BibliographyDistributionEntry[],
  librarySources?: readonly Source[],
  profiles?: readonly SourceProfile[]
): Promise<ProjectedScope> | ProjectedScope[] {
  if ("planningBrief" in inputOrManuscript) {
    return projectDocumentaryScope(inputOrManuscript);
  }
  return projectPersistedLegacyDistribution(
    inputOrManuscript,
    distribution ?? [],
    librarySources ?? [],
    profiles ?? []
  );
}

async function projectDocumentaryScope(
  input: ProjectBibliographyInput
): Promise<ProjectedScope> {
  const {
    planningBrief,
    librarySources,
    profiles,
    citations = [],
    relations = [],
    explorer,
    context = [],
    limitPerProbe = 1,
  } = input;
  const scopeId = planningScopeId(planningBrief);
  const verifiedCitationById = new Map(
    citations
      .filter((citation) => citation.verificationStatus === "verified")
      .map((citation) => [citation.id, citation])
  );

  const relevantRelations = relations.filter((relation) => {
    if (!relationAppliesToScope(relation, planningBrief.projectId, scopeId)) return false;
    if (relation.citationIds.length === 0) return false;
    return relation.citationIds.every((citationId) => verifiedCitationById.has(citationId));
  });
  const citationIds = unique(
    relevantRelations.flatMap((relation) => relation.citationIds)
  );

  const passages: ProjectedPassage[] = [];
  const exploredGapIds = new Set<number>();
  if (explorer) {
    const sharedContext = [
      planningBrief.question,
      planningBrief.intention,
      planningBrief.angleOrFunction,
      ...context,
    ]
      .filter((value): value is string => typeof value === "string" && value.trim().length > 0)
      .join("\n");

    for (const hypothesis of planningBrief.hypotheses) {
      if (hypothesis.status === "rejected") continue;
      const query = [hypothesis.statement, sharedContext].filter(Boolean).join("\n");
      const probes: CorroborationProbe[] = [
        "support",
        "contradiction",
        "qualification",
      ];
      for (const probe of probes) {
        const retrieved = await explorer.retrieve({
          mode: "corroboration",
          query,
          probe,
          limit: limitPerProbe,
        });
        for (const passage of retrieved) {
          passages.push({
            passage,
            role: roleForProbe(passage.probe),
            query: hypothesis.statement,
          });
        }
      }
    }

    for (const [index, gap] of planningBrief.gaps.entries()) {
      const query = [gap.neededEvidence ?? gap.description, sharedContext]
        .filter(Boolean)
        .join("\n");
      const retrieved = await explorer.retrieve({
        mode: "exploration",
        query,
        limit: 1,
      });
      if (retrieved.length > 0) exploredGapIds.add(index);
      for (const passage of retrieved) {
        passages.push({ passage, role: "context", query: gap.description });
      }
    }
  }

  const dedupedPassages = dedupeProjectedPassages(passages);
  const projectedSourceIds = new Set<string>(planningBrief.sourceRefs);
  for (const citationId of citationIds) {
    const citation = verifiedCitationById.get(citationId);
    if (citation) projectedSourceIds.add(citation.sourceId);
  }
  for (const item of dedupedPassages) projectedSourceIds.add(item.passage.sourceId);
  for (const relation of relevantRelations) {
    for (const participant of relation.participants) {
      if (participant.kind === "source") projectedSourceIds.add(participant.id);
    }
  }

  const sourceById = new Map(librarySources.map((source) => [source.id, source]));
  const profileBySource = new Map(profiles.map((profile) => [profile.sourceId, profile]));
  const sources = [...projectedSourceIds]
    .map((sourceId) => projectSource(sourceId, sourceById.get(sourceId), profileBySource.get(sourceId)))
    .sort((left, right) => left.sourceId.localeCompare(right.sourceId));

  const gaps = planningBrief.gaps.map((gap) => gap.description);
  const unexploredAreas = planningBrief.gaps
    .filter((_, index) => !explorer || !exploredGapIds.has(index))
    .map((gap) => gap.description);

  return {
    scopeId,
    sources,
    passages: dedupedPassages,
    citationIds,
    sourceRelationIds: relevantRelations.map((relation) => relation.id),
    gaps,
    unexploredAreas,
  };
}

/**
 * Read adapter for workspaces written before Corpus V2. It never retrieves,
 * qualifies or creates documentary evidence and must not be used for new
 * planning decisions.
 */
function projectPersistedLegacyDistribution(
  manuscript: Manuscript,
  distribution: readonly BibliographyDistributionEntry[],
  librarySources: readonly Source[],
  profiles: readonly SourceProfile[]
): ProjectedScope[] {
  const nodeIds = new Set(collectNodeIds(manuscript.tree));
  const sourceById = new Map(librarySources.map((source) => [source.id, source]));
  const profileBySource = new Map(profiles.map((profile) => [profile.sourceId, profile]));
  const grouped = new Map<string, ProjectedSource[]>();

  for (const entry of distribution) {
    if (!nodeIds.has(entry.scopeId)) continue;
    const list = grouped.get(entry.scopeId) ?? [];
    list.push(
      projectSource(
        entry.sourceId,
        sourceById.get(entry.sourceId),
        profileBySource.get(entry.sourceId)
      )
    );
    grouped.set(entry.scopeId, list);
  }

  return [...grouped.entries()].map(([scopeId, sources]) => ({
    scopeId,
    sources,
    passages: [],
    citationIds: [],
    sourceRelationIds: [],
    gaps: [],
    unexploredAreas: [],
  }));
}

/** Ajoute uniquement les références canoniques de la projection à un plan existant. */
export function projectEditorialPlanReferences(
  plan: EditorialPlan,
  projection: ProjectedScope
): EditorialPlan {
  return {
    ...plan,
    citationIds: unique([...plan.citationIds, ...projection.citationIds]),
    sourceRelationIds: unique([
      ...plan.sourceRelationIds,
      ...projection.sourceRelationIds,
    ]),
  };
}

/**
 * Projection Writer : réutilise EvidencePack sans en faire une autorité.
 * Les relations contradictoires deviennent des objections ; leur traçabilité
 * canonique reste dans EditorialPlan.sourceRelationIds.
 */
export function buildEvidencePackFromProjection(
  projection: ProjectedScope,
  citations: readonly Citation[],
  relations: readonly ContentRelation[],
  supportingClaimIds: readonly string[] = []
): EvidencePack {
  const allowedCitationIds = new Set(projection.citationIds);
  const selectedCitations = citations.filter(
    (citation) =>
      allowedCitationIds.has(citation.id) && citation.verificationStatus === "verified"
  );
  const relationById = new Map(relations.map((relation) => [relation.id, relation]));
  const objections = projection.sourceRelationIds
    .map((relationId) => relationById.get(relationId))
    .filter((relation): relation is ContentRelation => relation?.type === "contradicts")
    .map((relation) => ({
      statement: relation.description,
      sourceId: relation.participants.find((participant) => participant.kind === "source")?.id,
    }));

  return {
    sourceIds: unique([
      ...projection.sources.map((source) => source.sourceId),
      ...selectedCitations.map((citation) => citation.sourceId),
    ]),
    keyCitations: selectedCitations.map((citation) => ({
      sourceId: citation.sourceId,
      quote: citation.quote,
      pageRange:
        citation.locator.kind === "page" ? citation.locator.value : undefined,
      context: citation.context,
    })),
    supportingClaimIds: [...supportingClaimIds],
    objections,
    authorNotes:
      projection.unexploredAreas.length > 0
        ? `Zones documentaires encore ouvertes : ${projection.unexploredAreas.join(" ; ")}`
        : undefined,
  };
}

function planningScopeId(brief: PlanningBrief): string {
  if (brief.scopeRef.kind === "node") return brief.scopeRef.nodeId;
  if (brief.scopeRef.kind === "plan_entry") return brief.scopeRef.planEntryId;
  return brief.scopeRef.manuscriptId;
}

function relationAppliesToScope(
  relation: ContentRelation,
  projectId: string,
  scopeId: string
): boolean {
  if (relation.scope.projectId !== projectId) return false;
  if (relation.scope.level === "project") return true;
  if (relation.scope.level === "section") return relation.scope.sectionId === scopeId;
  return relation.scope.paragraphId === scopeId || relation.scope.sectionId === scopeId;
}

function roleForProbe(probe: CorroborationProbe | undefined): DocumentaryRole {
  if (probe === "contradiction" || probe === "counterexample") return "contradicts";
  if (probe === "qualification" || probe === "alternative") return "qualifies";
  if (probe === "support") return "supports";
  return "context";
}

function projectSource(
  sourceId: string,
  source: Source | undefined,
  profile: SourceProfile | undefined
): ProjectedSource {
  return {
    sourceId,
    title: source?.title ?? sourceId,
    authors: source?.authors ?? [],
    subjects: profile?.subjects ?? [],
    concepts: profile?.concepts ?? [],
    abstract: profile?.abstract,
  };
}

function dedupeProjectedPassages(passages: ProjectedPassage[]): ProjectedPassage[] {
  const seen = new Set<string>();
  return passages.filter((item) => {
    const key = `${item.passage.id}:${item.role}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function unique(values: readonly string[]): string[] {
  return [...new Set(values)];
}
